<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>FanControl.DeepCoolDigital.Core</RootNamespace>
    <AssemblyName>FanControl.DeepCoolDigital.Core</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

</Project>
