<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <AssemblyName>DeepCoolDigitalProbe</AssemblyName>
    <RootNamespace>DeepCoolDigitalProbe</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HidSharp">
      <HintPath>..\..\lib\HidSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="FanControl.IPC">
      <HintPath>..\..\lib\FanControl.IPC.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Grpc.Core.Api">
      <HintPath>..\..\lib\Grpc.Core.Api.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="GrpcDotNetNamedPipes">
      <HintPath>..\..\lib\GrpcDotNetNamedPipes.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Google.Protobuf">
      <HintPath>..\..\lib\Google.Protobuf.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\..\lib\System.Memory.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Buffers">
      <HintPath>..\..\lib\System.Buffers.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Numerics.Vectors">
      <HintPath>..\..\lib\System.Numerics.Vectors.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>..\..\lib\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FanControl.DeepCoolDigital.Core\FanControl.DeepCoolDigital.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="setup-probe.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
