<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <AssemblyName>DeepCoolDigitalProbe</AssemblyName>
    <RootNamespace>DeepCoolDigitalProbe</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HidSharp">
      <HintPath>..\..\lib\HidSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
